### ISSUE TITLE
Scroll horizontal

### ISSUE THREAD

**Issue by Nidev-lab** [NicolasGalia/Coder-Coffe#10]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

No encontrar un scroll horizontal.

## Resultado actual

Se encuentra un scroll horizontal.

## Posible solucion

* Agregar "gx-0" si se usa "row", ya que elimina el scroll creado por "row" .
    Captura con solucion
![image](https://user-images.githubusercontent.com/53904695/235729605-2daa4e10-beee-484a-817a-0d62d1db99ce.png)

![image](https://user-images.githubusercontent.com/53904695/235729796-5a826149-9cdb-4126-9eb5-f864691e5908.png)

![image](https://user-images.githubusercontent.com/53904695/235729995-40a05f0f-4893-4b99-bea9-f21307f4dd22.png)

## Captura de error

![image](https://user-images.githubusercontent.com/53904695/235728132-086b9e3a-e3e0-44b4-9fe3-91bc15bc3cb2.png)

![image](https://user-images.githubusercontent.com/53904695/235728318-aff5c07c-0f9c-4346-8794-47311f2f556d.png)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by NicolasGalia** [comment]
Resulto el Scroll horizontal! utilizamos overflow: auto al div.

![Captura de pantalla 2023-05-11 124524](https://github.com/NicolasGalia/Coder-Coffe/assets/107409269/db04a10e-823d-4cc7-8747-4a22f326971d)
