### ISSUE TITLE
Botones sin accion

### ISSUE THREAD

**Issue by Nidev-lab** [NicolasGalia/Coder-Coffe#11]
## Proceso

1. Ingrese a la pagina.
2. Navegue hasta el final.

## Resultado esperado

Que al hacer click los botones redirijan a sus respectivas secciones.

## Resultado actual

Los botones no cumplen ninguna función.

## Captura

![image](https://user-images.githubusercontent.com/53904695/236953225-68ab6bca-db86-4f58-aefe-e8834f4d29b3.png)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by NicolasGalia** [comment]
Buenas, que tal? ya solucionado los botones, saque los navlink porque sino pierde las class el texto y no queda acorde a la pag, agregue useNavigate y navlink y dirigí el logo hacia sobreNosotros para demostrar que se puede utilizar!

**Comment by NicolasGalia** [comment]
- 
![Captura de pantalla 2023-05-11 112240](https://github.com/NicolasGalia/Coder-Coffe/assets/107409269/34d8c5c8-d399-4e63-9a8a-f51344056cf9)

**Comment by Nidev-lab** [comment]
Perfecto! Traten de solucionar el issue que quedo pendiente y después peguelen una mirada al repo del back que quedo una issue cargada, con eso ya terminariamos.
